version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:v4
    steps:
      - checkout
      - run:
          name: Build
          command: make all
      - run:
          name: Unit Test
          command: make run-unit-tests
