version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:v4
    steps:
      - checkout
      - run:
          name: Build
          command: make all
      - run:
          name: Unit Test
          command: ls -ltrha /root/project/3rd-party/SDL2_image-2.0.1/lib && make run-unit-tests
